module.exports = async () => {
  return [
    {
      first_name: 'Razvan-George-Catalin',
      last_name: 'Ifrim',
      birthday: new Date("1984-04-18"),
      email: 'ggcifrim70@gmail.com',
      salary: 3500,
      coach_category: 'Antrenor emerit',
      license_number: 121,
    },
    {
      first_name: 'Teodora',
      last_name: 'Velea',
      birthday: new Date("1991-02-14"),
      email: 'teodoravelea@yahoo.com',
      salary: 2300,
      coach_category: 'Instructor sportiv',
      license_number: 133,
    },
    {
      first_name: 'Victor',
      last_name: 'Ocnarescu',
      birthday: new Date("1989-05-22"),
      email: 'ocnarescuvic@yahoo.com',
      salary: 4000,
      coach_category: 'Antrenor emerit',
      license_number: 198,
    },
    {
      first_name: 'Mihailov',
      last_name: 'Mihai',
      birthday: new Date("1990-12-04"),
      email: 'mmihailov@yahoo.com',
      salary: 2000,
      coach_category: 'Instructor sportiv',
      license_number: 251,
    },
    {
      first_name: 'Maya',
      last_name: 'Preda',
      birthday: new Date("1995-02-22"),
      email: 'prdmaya@gmail.com',
      salary: 2500,
      coach_category: 'Instructor sportiv',
      license_number: 369,
    },
    {
      first_name: 'Vlad',
      last_name: 'Barbu',
      birthday: new Date("1975-07-13"),
      email: 'vladbarbu@yahoo.com',
      salary: 3000,
      coach_category: 'Antrenor national',
      license_number: 3423,
    },
    {
      first_name: 'Ana-Maria',
      last_name: 'Vladescu',
      birthday: new Date("1981-05-23"),
      email: 'vladescuanau@gmail.com',
      salary: 3000,
      coach_category: 'Fara categorie',
      license_number: 756756,
    },
    {
      first_name: 'Bogdan',
      last_name: 'Posedaru',
      birthday: new Date("1990-03-05"),
      email: 'posedarubogdan@yahoo.com',
      salary: 3000,
      coach_category: 'Antrenor emerit',
      license_number: 24234,
    },
    {
      first_name: 'Dan',
      last_name: 'Enuta',
      birthday: new Date("1995-11-05"),
      email: 'enutadan@gmail.com',
      salary: 3000,
      coach_category: 'Antrenor national',
      license_number: 6578,
    },
    {
      first_name: 'Emilian',
      last_name: 'Frasina',
      birthday: new Date("1974-02-12"),
      email: 'emifrasina@gmail.com',
      salary: 3000,
      coach_category: 'Antrenor national',
      license_number: 5332,
    },
    {
      first_name: 'Panea',
      last_name: 'Ionut-Valentin',
      birthday: new Date("1974-02-12"),
      email: 'ionutpanea@ase.com',
      salary: 3000,
      coach_category: 'Antrenor national',
      license_number: 489,
    }
  ];
};
