const { hashSync } = require('bcryptjs');

module.exports = async () => {
  return [
    {
      email: 'michael@email.com',
      name: 'Andrada Popa',
      role: 'admin',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      birthday: new Date('1999-04-14'),
    },
    {
      email: 'pam@email.com',
      first_name: 'Marian',
      last_name: 'Popescu',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'Fara categorie',
      birthday: new Date('1999-04-14'),
    },
    {
      email: 'mateimarinescu@gmail.com',
      first_name: 'Matei',
      last_name: 'Marinescu',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'I',
      birthday: new Date('2005-04-02'),
    },
    {
      email: 'aandreescu@gmail.com',
      first_name: 'Andreea',
      last_name: 'Andreescu',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'II',
      birthday: new Date('2006-03-08'),
    },
    {
      email: 'ursachetdr@gmail.com',
      first_name: 'Tudor',
      last_name: 'Ursache',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'Candidat de maestru',
      birthday: new Date('2008-12-12'),
    },
    {
      email: 'bastonemilia@gmail.com',
      first_name: 'Florina',
      last_name: 'Baston',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'Fara categorie',
      birthday: new Date('2006-08-14'),
    },
    {
      email: 'vldvld@gmail.com',
      first_name: 'Simon',
      last_name: 'Vladescu',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'III',
      birthday: new Date('2005-10-07'),
    },
    {
      email: 'mapopa@gmail.com',
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'II',
      birthday: new Date('2010-09-15'),
    },
    {
      email: 'dolanaandrei@ase.ro',
      first_name: 'Andrei-Theodor',
      last_name: 'Dolana',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'Maestru FIDE',
      birthday: new Date('1999-04-14'),
    },
    {
      email: 'clarisabejan@ase.ro',
      first_name: 'Clarisa-Iustina',
      last_name: 'Bejan',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'I',
      birthday: new Date('1999-08-11'),
    },
    {
      email: 'irinabulmaga@gmail.com',
      first_name: 'Irina',
      last_name: 'Bulmaga',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'Mare Maestru',
      birthday: new Date('1993-09-20'),
    },
    {
      email: 'radutoma@ase.ro',
      first_name: 'Radu-Cristian',
      last_name: 'Toma',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'Maestru International',
      birthday: new Date('1998-08-10'),
    },
    {
      email: 'mariapopovici@gmai.com',
      first_name: 'Clara',
      last_name: 'Popovici',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'Fara categorie',
      birthday: new Date('2015-07-02'),
    },
    {
      email: 'amciolacu@gmail.com',
      first_name: 'Alessia-Mihaela',
      last_name: 'Ciolacu',
      role: 'player',
      password: hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      category: 'Maestru FIDE',
      birthday: new Date('2004-11-27'),
    },
    // {
    //   email: 'mihai2012@gmail.com',
    //   first_name: 'Mihai',
    //   last_name: 'Dragomir',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'III',
    //   birthday: new Date('2012-04-04'),
    // },
    // {
    //   email: 'marinmacaveiu@gmail.com',
    //   first_name: 'Marius',
    //   last_name: 'Macaveiu',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'Fara categorie',
    //   birthday: new Date('2016-02-15'),
    // },
    // {
    //   email: 'papaescualexandra@gmail.com',
    //   first_name: 'Alexandra',
    //   last_name: 'Papaescu',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'II',
    //   birthday: new Date('2011-06-17'),
    // },
    // {
    //   email: 'ioanahododi@gmail.com',
    //   first_name: 'Ioana',
    //   last_name: 'Hododi',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'I',
    //   birthday: new Date('2004-03-14'),
    // },
    // {
    //   email: 'razvancarpet@yahoo.com',
    //   first_name: 'Razvan',
    //   last_name: 'Carpet',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'Maestru National',
    //   birthday: new Date('2006-12-04'),
    // },
    // {
    //   email: 'mmanusca@gmail.com',
    //   first_name: 'Madalina-Maria',
    //   last_name: 'Anusca',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'Maestru National',
    //   birthday: new Date('1992-08-17'),
    // },
    // {
    //   email: 'mariaursente@gmail.com',
    //   first_name: 'Maria',
    //   last_name: 'Ursente',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'Maestru FIDE',
    //   birthday: new Date('1992-04-04'),
    // },
    // {
    //   email: 'mirceaeparligras@gmail.com',
    //   first_name: 'Mircea-Emilian',
    //   last_name: 'Parligras',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'Mare Maestru',
    //   birthday: new Date('2010-09-15'),
    // },
    // {
    //   email: 'radufluerariu@ase.ro',
    //   first_name: 'Radu-Cristian',
    //   last_name: 'Fluerariu',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'Maestru FIDE',
    //   birthday: new Date('2002-01-10'),
    // },
    // {
    //   email: 'alexiacriveanu@gmail.com',
    //   first_name: 'Alexia',
    //   last_name: 'Criveanu',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'Fara categorie',
    //   birthday: new Date('2015-06-04'),
    // },
    // {
    //   email: 'andreinegrean@gmail.com',
    //   first_name: 'Andrei',
    //   last_name: 'Negrean',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'Fara categorie',
    //   birthday: new Date('2014-02-02'),
    // },
    // {
    //   email: 'manolachevld@gmail.com',
    //   first_name: 'Vladimir',
    //   last_name: 'Manolache',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'Fara categorie',
    //   birthday: new Date('2014-02-16'),
    // },
    // {
    //   email: 'frsnelvira@gmail.com',
    //   first_name: 'Elvira',
    //   last_name: 'Frasina',
    //   role: 'player',
    //   password: hashSync('supersecretpassword'),
    //   active: true,
    //   confirmed: true,
    //   category: 'II',
    //   birthday: new Date('2014-09-12'),
    // },
  ];
};
