const { Area, Player, Sport, Identity } = require('../../models');

module.exports = async () => {
  const players = await Identity.find({ role: 'player' });
  const areas = await Area.find();
  const sport = await Sport.find();

  return [
    {
      player1: players[0]['_id'],
      player2: players[5]['_id'],
      arbiter_name: 'Chirila Radu',
      date: new Date('2022-06-01'),
      location: areas[0]['_id'],
      sport: sport[0],
    },
    {
      player1: players[0]['_id'],
      player2: players[2]['_id'],
      arbiter_name: 'Nicula Ioan',
      date: new Date('2022-06-01'),
      location: areas[1]['_id'],
      sport: sport[1],
    },
    {
      player1: players[1]['_id'],
      player2: players[3]['_id'],
      arbiter_name: 'Muntean Ciprian',
      date: new Date('2022-06-01'),
      location: areas[2]['_id'],
      sport: sport[2],
    },
    {
      player1: players[4]['_id'],
      player2: players[2]['_id'],
      arbiter_name: 'Popescu Andrei',
      date: new Date('2022-06-01'),
      location: areas[1]['_id'],
      sport: sport[0],
    },
    {
      player1: players[1]['_id'],
      player2: players[5]['_id'],
      arbiter_name: 'Chirila Radu',
      date: new Date('2022-06-01'),
      location: areas[0]['_id'],
      sport: sport[1],
    },
    {
      player1: players[1]['_id'],
      player2: players[2]['_id'],
      arbiter_name: 'Nicula Ioan',
      date: new Date('2022-06-02'),
      location: areas[1]['_id'],
      sport: sport[2],
    },
    {
      player1: players[2]['_id'],
      player2: players[3]['_id'],
      arbiter_name: 'Muntean Ciprian',
      date: new Date('2022-06-02'),
      location: areas[2]['_id'],
      sport: sport[2],
    },
    {
      player1: players[4]['_id'],
      player2: players[2]['_id'],
      arbiter_name: 'Popescu Andrei',
      date: new Date('2022-06-02'),
      location: areas[1]['_id'],
      sport: sport[1],
    },
    {
      player1: players[3]['_id'],
      player2: players[5]['_id'],
      arbiter_name: 'Chirila Radu',
      date: new Date('2022-06-03'),
      location: areas[0]['_id'],
      sport: sport[0],
    },
    {
      player1: players[3]['_id'],
      player2: players[2]['_id'],
      arbiter_name: 'Nicula Ioan',
      date: new Date('2022-06-03'),
      location: areas[1]['_id'],
      sport: sport[1],
    },
    {
      player1: players[4]['_id'],
      player2: players[3]['_id'],
      arbiter_name: 'Muntean Ciprian',
      date: new Date('2022-06-03'),
      location: areas[2]['_id'],
      sport: sport[1],
    },
    {
      player1: players[4]['_id'],
      player2: players[5]['_id'],
      arbiter_name: 'Popescu Andrei',
      date: new Date('2022-06-03'),
      location: areas[1]['_id'],
      sport: sport[0],
    },
    {
      player1: players[6]['_id'],
      player2: players[5]['_id'],
      arbiter_name: 'Chirila Radu',
      date: new Date('2022-06-04'),
      location: areas[0]['_id'],
      sport: sport[2],
    },
    {
      player1: players[7]['_id'],
      player2: players[2]['_id'],
      arbiter_name: 'Nicula Ioan',
      date: new Date('2022-06-04'),
      location: areas[1]['_id'],
      sport: sport[1],
    },
    {
      player1: players[6]['_id'],
      player2: players[3]['_id'],
      arbiter_name: 'Muntean Ciprian',
      date: new Date('2022-06-04'),
      location: areas[2]['_id'],
      sport: sport[2],
    },
    {
      player1: players[7]['_id'],
      player2: players[2]['_id'],
      arbiter_name: 'Popescu Andrei',
      date: new Date('2022-06-05'),
      location: areas[1]['_id'],
      sport: sport[1],
    },
    {
      player1: players[7]['_id'],
      player2: players[5]['_id'],
      arbiter_name: 'Chirila Radu',
      date: new Date('2022-06-05'),
      location: areas[0]['_id'],
      sport: sport[2],
    },
    {
      player1: players[8]['_id'],
      player2: players[2]['_id'],
      arbiter_name: 'Nicula Ioan',
      date: new Date('2022-06-05'),
      location: areas[1]['_id'],
      sport: sport[1],
    },
    {
      player1: players[8]['_id'],
      player2: players[3]['_id'],
      arbiter_name: 'Muntean Ciprian',
      date: new Date('2022-06-05'),
      location: areas[2]['_id'],
      sport: sport[0],
    },
    {
      player1: players[9]['_id'],
      player2: players[2]['_id'],
      arbiter_name: 'Popescu Andrei',
      date: new Date('2022-06-05'),
      location: areas[1]['_id'],
      sport: sport[0],
    },
  ];
};
