module.exports = async () => {
  return [
    {
      first_name: 'Matei',
      last_name: 'Marinescu',
      birthday: new Date('2005-04-02'),
      email: 'mateimarinescu@gmail.com',
      category: 'I',
    },
    {
      first_name: 'Andreea',
      last_name: 'Andreescu',
      birthday: new Date('2006-03-08'),
      email: 'aandreescu@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Tudor',
      last_name: 'Ursache',
      birthday: new Date('2008-12-12'),
      email: 'ursachetdr@gmail.com',
      category: 'Candidat de maestru',
    },
    {
      first_name: 'Florina',
      last_name: 'Baston',
      birthday: new Date('2006-08-14'),
      email: 'bastonemilia@gmail.com',
      category: 'Fara categorie',
    },
    {
      first_name: 'Simon',
      last_name: 'Vladescu',
      birthday: new Date('2005-10-07'),
      email: 'vldvld@gmail.com',
      category: 'III',
    },
    {
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      birthday: new Date('2010-09-15'),
      email: 'mapopa@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Andrei-Theodor',
      last_name: 'Dolana',
      birthday: new Date('1999-04-14'),
      email: 'dolanaandrei@ase.ro',
      category: 'Maestru FIDE',
    },
    {
      first_name: 'Clarisa-Iustina',
      last_name: 'Bejan',
      birthday: new Date('1999-08-11'),
      email: 'clarisabejan@ase.ro',
      category: 'I',
    },
    {
      first_name: 'Irina',
      last_name: 'Bulmaga',
      birthday: new Date('1993-09-20'),
      email: 'irinabulmaga@gmail.com',
      category: 'Mare Maestru',
    },
    {
      first_name: 'Radu-Cristian',
      last_name: 'Toma',
      birthday: new Date('1998-08-10'),
      email: 'radutoma@ase.ro',
      category: 'Maestru International',
    },
    {
      first_name: 'Clara',
      last_name: 'Popovici',
      birthday: new Date('2015-07-02'),
      email: 'mariapopovici@gmai.com',
      category: 'Fara categorie',
    },
    {
      first_name: 'Alessia-Mihaela',
      last_name: 'Ciolacu',
      birthday: new Date('2004-11-27'),
      email: 'amciolacu@gmail.com',
      category: 'Maestru FIDE',
    },
    {
      first_name: 'Mihai',
      last_name: 'Dragomir',
      birthday: new Date('2012-04-04'),
      email: 'mihai2012@gmail.com',
      category: 'III',
    },
    {
      first_name: 'Marius',
      last_name: 'Macaveiu',
      birthday: new Date('2016-02-15'),
      email: 'marinmacaveiu@gmail.com',
      category: 'Fara categorie',
    },
    {
      first_name: 'Alexandra',
      last_name: 'Papaescu',
      birthday: new Date('2011-06-17'),
      email: 'papaescualexandra@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Ioana',
      last_name: 'Hododi',
      birthday: new Date('2004-03-14'),
      email: 'ioanahododi@gmail.com',
      category: 'I',
    },
    {
      first_name: 'Razvan',
      last_name: 'Carpet',
      birthday: new Date('2006-12-04'),
      email: 'razvancarpet@yahoo.com',
      category: 'Maestru National',
    },
    {
      first_name: 'Madalina-Maria',
      last_name: 'Anusca',
      birthday: new Date('1992-08-17'),
      email: 'mmanusca@gmail.com',
      category: 'Maestru National',
    },
    {
      first_name: 'Maria',
      last_name: 'Ursente',
      birthday: new Date('1992-04-04'),
      email: 'mariaursente@gmail.com',
      category: 'Maestru FIDE',
    },
    {
      first_name: 'Mircea-Emilian',
      last_name: 'Parligras',
      birthday: new Date('2010-09-15'),
      email: 'mirceaeparligras@gmail.com',
      category: 'Mare Maestru',
    },
    {
      first_name: 'Radu-Cristian',
      last_name: 'Fluerariu',
      birthday: new Date('2002-01-10'),
      email: 'radufluerariu@ase.ro',
      category: 'Maestru FIDE',
    },
    {
      first_name: 'Alexia',
      last_name: 'Criveanu',
      birthday: new Date('2015-06-04'),
      email: 'alexiacriveanu@gmail.com',
      category: 'Fara categorie',
    },
    {
      first_name: 'Andrei',
      last_name: 'Negrean',
      birthday: new Date('2014-02-02'),
      email: 'andreinegrean@gmail.com',
      category: 'Fara cateogorie',
    },
    {
      first_name: 'Vladimir',
      last_name: 'Manolache',
      birthday: new Date('2014-02-16'),
      email: 'manolachevld@gmail.com',
      category: 'Fara categorie',
    },
    {
      first_name: 'Elvira',
      last_name: 'Frasina',
      birthday: new Date('2014-09-12'),
      email: 'frsnelvira@gmail.com',
      category: 'II',
    },
  ];
};
